# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='login_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
