# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20161201_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expires_in',
            field=models.BigIntegerField(default=0),
        ),
    ]
