# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20161202_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='access_token',
        ),
    ]
