# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_member_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
