# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('dtype', models.CharField(choices=[('MY', '我自己的'), ('AT', '我关注的人')], max_length=2)),
                ('link', models.URLField(verbose_name='动态链接')),
                ('action', models.CharField(max_length=128, verbose_name='动态')),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('dynamicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dynamicer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mydynamic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '我的动态',
                'verbose_name_plural': '我的动态',
            },
        ),
    ]
