# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenicname', models.CharField(max_length=128, verbose_name='名称')),
                ('scenicaddress', models.CharField(max_length=255, verbose_name='地址')),
                ('country', models.CharField(max_length=128, verbose_name='国家')),
                ('province', models.CharField(max_length=128, verbose_name='省')),
                ('city', models.CharField(max_length=128, verbose_name='市')),
                ('scenictype', models.CharField(choices=[('CR', '文物古迹'), ('CG', '古典园林'), ('LA', '文学艺术'), ('RC', '宗教文化'), ('RL', '城乡风貌'), ('MF', '现代设施'), ('FC', '民俗风情'), ('ES', '饮食与购物类')], max_length=2)),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('scenic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.Scenic')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('tag', 'scenic')]),
        ),
        migrations.AlterIndexTogether(
            name='tag',
            index_together=set([('tag', 'scenic')]),
        ),
    ]
