# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0002_auto_20161129_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenic',
            name='scenicname',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
