# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0003_auto_20161129_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenic',
            name='scenicaddress',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=64),
        ),
    ]
