# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0004_auto_20161129_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenic',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='full/'),
        ),
    ]
