# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0005_scenic_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='picture/')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Picture',
            },
        ),
        migrations.AlterField(
            model_name='scenic',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='picture',
            name='scenic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenic_pic', to='scenic.Scenic'),
        ),
    ]
